user-password:
    allenzch: ENC[AES256_GCM,data:ayjwF5miHK1uvPNXoY/+eib/YQp+EXxxdTjj5POBE6f7YlBux3i0uNfaj5iQjlznJeU7z2hk74au5hAdfcEKP6Gpq+nM4/wHmZAwBRBIHYhYmOsSUKFJOOIkWcPCOjMeccIfOJlEDtmC0w==,iv:o/xDjGJut/2B/3Hdha9rnuACD59AeETajqilvXxk0q4=,tag:sYjCAebWoXkTic6prj8Tpw==,type:str]
    root: ENC[AES256_GCM,data:5Btwfr+/DfbLJT4rIqf6F9VVbsqZ31+UOIoB5nwSf+jGvfq2S54+ssZsLxsN+w8uzFeJdz5D0DGBZNPtSQsdLwnMnuhI+iid5kpvkMiC1f2oFIWBjmtCpZgQis0er+npzmLxaD2H6PQLbg==,iv:RR16ySnrsNJ7BNDtF4sIg7vwLgUZqYf+bU6TcM8WKOI=,tag:s8UahuwYOuVz05uaTofRkA==,type:str]
enthalpy-private-key-pem:
    allenzch: ENC[AES256_GCM,data:A6y1N3lVarIsVUpEXbD/iUKwCxFj6ZwRfhIqrg4qyWBxhr0xCs6BP7x/U5KXvs+7hYJx3ziRfkk8ceGZHczbQ0sk05x8h3K5fDEDhcg/ugE0gFTpJYEcRjz5vTqdXes0ENrXy3fn+eUIFZQHp+MEpln1x/iLTnw=,iv:vEnPHoePdMbu5NIXUa4cg3/CZMYoDoQp+Eipu9gH8zI=,tag:JFHPxLdjnaoiT0CgCtAbkg==,type:str]
cloudflare:
    api-token: ENC[AES256_GCM,data:tteEMSQ9774fGDNKrvNzYRhDmzysm3h+uDpvP3cApcJa+/L7dMptuQ==,iv:iZ0VE5weRwWwKWA6pNnilJeIiSsgzC9hmC2nMtTT7So=,tag:G20f1Qm/UohbmzMAklRR7Q==,type:str]
sops:
    age:
        - recipient: age1u45uunqcxs6urd0tyr62hxpawmr508zul9pducwe0dnr0fucy40ql64jqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYk5lM0NMdFpTWTRIbG5n
            S05IUWRsM3B6YXQvVlRiUVlhRnN2d3N5RGo0CmhlSFFiMUNFbjl0OVBpanpabmFo
            Ym1Sank5TURhNEpMRndFeVFuclpDc0EKLS0tIG9WWDhUbExXODFyNTVYWHM2NTh5
            S2xiRFgwNms2Snd4SDRGckRXcHhDNW8KnhyoZwG+4NSjaePaE6xLxcE+5rPEDzzd
            0JvfepCKI7i8qX8xsT2UAtJIxRQ8UAd84VFPA7xXVB6L1NKkYl9pLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T10:23:50Z"
    mac: ENC[AES256_GCM,data:zrbWGFCJ9VJxcCVa8RXm76lPW7WrXxDf2Fv4Cj3KdAnnmYhYxpEawUbgvi57EAYrEaF8zp967wPoIVhjU0o+6JGVqWbfKCccYJaIIGdg4oqX2YlWsDEh8pSfRPpn0ZkvWBSKGbaJUdeDNKV4LjwFU/SNOlbbGw7gF4hwefZmPOs=,iv:hfBSm0foVxBdbcq0+VswbL1lItwvUkwGm/wkz6nc0Vo=,tag:XCTgy8yfTru0dVPhOH5wNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
