user-password:
    allenzch: ENC[AES256_GCM,data:ayjwF5miHK1uvPNXoY/+eib/YQp+EXxxdTjj5POBE6f7YlBux3i0uNfaj5iQjlznJeU7z2hk74au5hAdfcEKP6Gpq+nM4/wHmZAwBRBIHYhYmOsSUKFJOOIkWcPCOjMeccIfOJlEDtmC0w==,iv:o/xDjGJut/2B/3Hdha9rnuACD59AeETajqilvXxk0q4=,tag:sYjCAebWoXkTic6prj8Tpw==,type:str]
    root: ENC[AES256_GCM,data:5Btwfr+/DfbLJT4rIqf6F9VVbsqZ31+UOIoB5nwSf+jGvfq2S54+ssZsLxsN+w8uzFeJdz5D0DGBZNPtSQsdLwnMnuhI+iid5kpvkMiC1f2oFIWBjmtCpZgQis0er+npzmLxaD2H6PQLbg==,iv:RR16ySnrsNJ7BNDtF4sIg7vwLgUZqYf+bU6TcM8WKOI=,tag:s8UahuwYOuVz05uaTofRkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u45uunqcxs6urd0tyr62hxpawmr508zul9pducwe0dnr0fucy40ql64jqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYk5lM0NMdFpTWTRIbG5n
            S05IUWRsM3B6YXQvVlRiUVlhRnN2d3N5RGo0CmhlSFFiMUNFbjl0OVBpanpabmFo
            Ym1Sank5TURhNEpMRndFeVFuclpDc0EKLS0tIG9WWDhUbExXODFyNTVYWHM2NTh5
            S2xiRFgwNms2Snd4SDRGckRXcHhDNW8KnhyoZwG+4NSjaePaE6xLxcE+5rPEDzzd
            0JvfepCKI7i8qX8xsT2UAtJIxRQ8UAd84VFPA7xXVB6L1NKkYl9pLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-20T08:45:02Z"
    mac: ENC[AES256_GCM,data:GwZ2wy4wfxzEdBb804xi5GaFPGAUCTD1lQuBjZL84cpaNNuH+GXm+KZ8cN6v2ZXxbOlMJkQ0zXaJC3yWX3xrIssLCvmAzbw6Gce2g6wbziyxMn1f7YJ0WCOzKEIdhrGzohfDIFuknjsyu+oqz5W0k92BfnoBCCo1ysNL/hmY6SU=,iv:1rRLFOxnmRKlANpRqzDrZec3ffbcWHYg/AIICMk6J5g=,tag:eGC7ftajJLEXishVoTmLZw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
