user-password:
    allenzch: ENC[AES256_GCM,data:ayjwF5miHK1uvPNXoY/+eib/YQp+EXxxdTjj5POBE6f7YlBux3i0uNfaj5iQjlznJeU7z2hk74au5hAdfcEKP6Gpq+nM4/wHmZAwBRBIHYhYmOsSUKFJOOIkWcPCOjMeccIfOJlEDtmC0w==,iv:o/xDjGJut/2B/3Hdha9rnuACD59AeETajqilvXxk0q4=,tag:sYjCAebWoXkTic6prj8Tpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u45uunqcxs6urd0tyr62hxpawmr508zul9pducwe0dnr0fucy40ql64jqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYk5lM0NMdFpTWTRIbG5n
            S05IUWRsM3B6YXQvVlRiUVlhRnN2d3N5RGo0CmhlSFFiMUNFbjl0OVBpanpabmFo
            Ym1Sank5TURhNEpMRndFeVFuclpDc0EKLS0tIG9WWDhUbExXODFyNTVYWHM2NTh5
            S2xiRFgwNms2Snd4SDRGckRXcHhDNW8KnhyoZwG+4NSjaePaE6xLxcE+5rPEDzzd
            0JvfepCKI7i8qX8xsT2UAtJIxRQ8UAd84VFPA7xXVB6L1NKkYl9pLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-13T13:17:16Z"
    mac: ENC[AES256_GCM,data:IkWLYhoGDS5mNBWuF1+DWkZCV3AjcM1KiyBhmhrlnXPbOk2O1D20R8aj/9wxUWAIqYzGjYu4DmvpZ1+KNSbZ1aHIKW2sb0/Fk/k9xcJqPmygWvjhjLxa0y1rPQefCORcWJsjKiuXv3cLXrGGvzyryDaL81OzwCuBpldXy0B6Kb8=,iv:HDi9tZhmQMK4FuVew5Ze5yC7g90mMzLmIm7xBHt1B/g=,tag:dBUsF4OYlcmLl55DFAYzVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
